const puns = [
    "I'm reading a book on anti-gravity. It's impossible to put down!",
    "I'm on a seafood diet. I see food and I eat it.",
    "Did you hear about the mathematician who’s afraid of negative numbers? He'll stop at nothing to avoid them.",
    "Why don’t scientists trust atoms? Because they make up everything!",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Parallel lines have so much in common. It’s a shame they’ll never meet.",
    "My wife told me I should do lunges to stay in shape. That would be a big step forward.",
    "Why do bees hum? Because they don't know the words.",
    "If you see a robbery at an Apple Store does that make you an iWitness?",
    "I would avoid the sushi if I were you. It’s a little fishy.",
    "Want to hear a joke about construction? I’m still working on it.",
    "I used to play piano by ear, but now I use my hands.",
    "Having sex in an elevator is wrong on so many levels.",
    "I'm terrified of elevators, so I’m going to start taking steps to avoid them.",
    "I used to be a baker, but I couldn't make enough dough.",
    "My ceiling isn’t the best, but it’s up there.",
    "I used to hate facial hair, but then it grew on me.",
    "I decided to sell my vacuum cleaner—it was just gathering dust!",
    "I had a neck brace fitted years ago and I’ve never looked back since.",
    "You can’t run through a campsite. You can only ran, because it’s past tents.",
    "I’m reading a book on the history of glue – can’t put it down.",
    "Did you hear about the guy who invented the knock-knock joke? He won the 'no-bell' prize.",
    "I’ve got a great joke about time travel, but you didn't like it.",
    "A termite walks into a bar and asks, 'Is the bartender here?'",
    "I used to be addicted to soap, but I’m clean now.",
    "The rotation of the earth really makes my day.",
    "I’m only friends with 25 letters of the alphabet. I don’t know Y.",
    "I told my computer I needed a break, and now it won’t stop sending me Kit-Kat ads.",
    "I’m no cheetah, you’re lion!",
    "Singing in the shower is fun until you get soap in your mouth. Then it's a soap opera.",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "I’d tell you a chemistry joke but I know I wouldn’t get a reaction.",
    "I tried to catch fog yesterday, Mist.",
    "I’m not a big fan of stairs. They’re always up to something.",
    "I told my suitcase there will be no vacation this year. Now I’m dealing with emotional baggage.",
    "If you've seen one shopping center, you've seen a mall.",
    "I once got into a fight with a broken elevator. I took it to another level.",
    "I’m so good at sleeping, I can do it with my eyes closed.",
    "I don't trust stairs because they're always up to something.",
    "Why couldn’t the leopard play hide and seek? Because he was always spotted.",
    "I'm no photographer, but I can picture us together.",
    "I wasn't originally going to get a brain transplant, but then I changed my mind.",
    "This graveyard looks overcrowded. People must be dying to get in.",
    "Why don’t skeletons fight each other? They don’t have the guts.",
    "I used to be a banker, but I lost interest.",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "I don't play soccer because I enjoy the sport. I'm just doing it for kicks!",
    "Becoming a vegetarian is a huge missed steak.",
    "Why do cows have hooves instead of feet? Because they lactose.",
    "I would tell you a construction pun, but I'm still working on it."
];

function showRandomPun() {
    const randomIndex = Math.floor(Math.random() * puns.length);
    document.getElementById('punDisplay').innerText = puns[randomIndex];
}
